/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        gradientForm: "#A376F1",
        borderGray: "#D1D5DB",
        primary: "#8353D2",
        darkLavender: "#72568D",
        secondary: "#F7F4FD",
        darkSecondary: "#291826",
        darkBg: "#3F2F3B",
        darkerBg: "#342530",
        tertiary: "#EADDF8",
        dark: "#1E0C1B",
        bgColor: "#82ccdd",
        warning: "#f0d500",
        danger: "#EC514C",
        success: "#4DB462",
        darkMintGreen: "#27C267",
        white: "#FFFFFF",
        darkText: "#BDBDBD",
        darkerText: "#716B6F",
        grayLight: "#717171",
        gray0: "#F7F7F7",
        gray1: "#CACACF",
        gainsboro: "#ddd",
        grayWhite: "#F0F0F0",
        gray: "#40494C",
        light: "#DBF6F6",
        maroonGray: "#DFDFDF",
        black: "#0a0a0a",
        transparent: "#00000000",
        customGray: "#40494C",
      },
    },
  },
  plugins: [],
};
